### ISSUE TITLE
crash on server side (jeid 1.0.0-6 / forge 14.23.4.2708)

### ISSUE THREAD

**Issue by Nightreaver** [DimensionalDevelopment/JustEnoughIDs#9] opened 2018-06-23 23:34 UTC
Hello

I made a modpack that works well on windows-client side, however, when I try to run in on my debian root, its crashing till i remove jeid which I cant really.

https://pastebin.com/PzextZih

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 3.16.0-6-amd64
  Java Version: 1.8.0_171, Oracle Corporation

JustEnoughIDs-1.0.0-6.jar

**Comment by ZombieHDGaming** [comment] 2018-06-23 23:36
Already fixed in the latest dev build.

**Comment by Runemoro** [comment] 2018-06-23 23:37
Duplicate of #1

**Closed by ZombieHDGaming** 2018-06-23 23:36 UTC

**Comment by Nightreaver** [comment] 2018-06-23 23:46
thanks a lot!
