### ISSUE TITLE
Crash With Pam's Harvestcraft

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/JustEnoughIDs#12] opened 2018-06-25 19:39 UTC
When you break any Pam's Harvestcraft Garden you crash straight to desktop

https://gist.github.com/TacticalUniverse/e1180b8258d2085e32ddab00e9814d32

**Comment by Robijnvogel** [comment] 2018-06-25 20:21
Duplicate of #7

**Closed by Robijnvogel** 2018-06-25 20:22 UTC
