### ISSUE TITLE
"A mod doesn't support extended biome ID's, report to Just Enough ID's

### ISSUE THREAD

**Issue by valoeghese** [DimensionalDevelopment/JustEnoughIDs#49] opened 2019-01-03 21:51 UTC
Biomes Mods Used: Biomes you go, Traverse, NetherEx, Project: Vibrant Journeys, Zoesteria Biomes

**Comment by Runemoro** [comment] 2019-01-03 21:54
Where do you see the message?

**Comment by valoeghese** [comment] 2019-01-11 03:41
I believe it's listed as a biome in Nature's Compass (another mod I'm using)

**Comment by ZombieHDGaming** [comment] 2019-02-23 20:01
Duplicate of #45 potentially

**Closed by ZombieHDGaming** 2019-02-23 20:01 UTC
