### ISSUE TITLE
Particle issues

### ISSUE THREAD

**Issue by xhatz** [DimensionalDevelopment/JustEnoughIDs#13] opened 2018-06-25 21:16 UTC
Hello there! As I was testing my modpack, I went through several crashs and problems, including some particle errors. Some particles, when breaking a block, were completely random (planks for a plant?)... and it seems like this mod is potentially a cause.

When doing my tests, I was playing around with my mods one by one, installing them progressively in order to try to see where the problem came from. I continued until I installed JEID to counter the max ID 4096 issue... but as soon as it was installed, some plants started using the wrong particles, it even crashed my game at some point...

I also tried with the rival **Not Enough IDs**, but **it seemed to work with this alternative**! No particle issues... I don't know where the bug could come from now...

Thanks! I hope this will get fixed :p!
_I have no log as it is mostly a visual bug..._

**Comment by Runemoro** [comment] 2018-06-26 03:02
Could you upload a crash report?

**Comment by Runemoro** [comment] 2018-06-27 06:35
Duplicate of #7

**Closed by Runemoro** 2018-06-27 06:35 UTC

**Comment by Robijnvogel** [comment] 2018-06-27 13:03
@Runemoro none of the other duplicates of #7 or #7 itself actually mention these "completely random and incorrect block breaking particles" being shown.

Maybe it'd be better to treat this issue as separate from #7 until we can see if a fix for #7 actually solves this particle issue as well? (even though, it is very likely related)
