### ISSUE TITLE
Crash with: java.lang.IllegalArgumentException: Cannot set property

### ISSUE THREAD

**Issue by DeadSix27** [DimensionalDevelopment/JustEnoughIDs#7] opened 2018-06-23 06:48 UTC
I can easily reproduce this crash by placing and destroying `jurassicraft:calamites_log_petrified` in the world.

However none of these crash dumps actually mentioned said mod or the block.

I tested the above reproducible issue with NEID(+VanillaFix) and JEID(+VanillaFix) and it only crashes with JEID.

And I had many similar looking crashes so I uploaded all the various crashlogs:

https://0x0.st/s9aV.txt
https://0x0.st/s9aW.txt
https://0x0.st/s9a4.txt
https://0x0.st/s9aJ.txt
https://0x0.st/s9ay.txt
https://0x0.st/s9at.txt

**Comment by Sunconure11** [comment] 2018-06-23 08:31
Report to the developers of Jurassicraft as well.

**Comment by jaz000** [comment] 2018-06-23 11:52
I have something looking very similar
when destroying deepsesonance mod ore I get a similar error and crash referencing rustic mod
https://pastebin.com/RkRVRpHQ

removing the rustic mod I can destroy the deepresonance ore block ok
switching back to NEIDs also works ok 

I'd rather use JEID though :) and it probably trump keeping rustic in the pack if it incompatibility with that mod

**Comment by Robijnvogel** [comment] 2018-06-23 12:34
Observations so far:
Crash is caused by trying to set a PropertyInteger to higher than 15 or at least higher than its maximum allowed value.
This typically happens with growth stages of plants and fluid levels of fluid blocks.

**Comment by karelmikie3** [comment] 2018-07-06 13:30
I seem to have something similar 
crash when breaking uranium crops from mystical agriculture: [crash](https://paste.ee/p/ZB54b)
crash when breaking mystical agriculture's growth accelerator: [crash](https://paste.ee/p/fpZAz)
crash when breaking SoulShardsRespawn's soul cage: [crash](https://paste.ee/p/E8ObL)

removing the mod actually mentioned in the crash log fixes the crash but then when the block is broken no sound played and if I remember well no particles displayed. (I also tested without optifine and foamfix)

**Comment by TacticalUniverse** [comment] 2018-07-10 15:24
Anytime frame this mod will be updated to fix this crash and bugs as I can post my new modpack or server without these crashes being fixed

**Comment by Runemoro** [comment] 2018-07-14 20:52
Fixed in dev.

**Closed by Runemoro** 2018-07-14 20:52 UTC
Labels: bug
