### ISSUE TITLE
Fail to start - Crash report

### ISSUE THREAD

**Issue by Kalonachan** [DimensionalDevelopment/JustEnoughIDs#129] opened 2020-03-27 03:09 UTC
When receiving this error code it would not tell me which mod was the actual issue so I had to individually go through all of the mods in my modpack to figure out which was causing the issue When I disabled JustEnoughIDs, it loaded properly without error.

In having even taken out The Lost Cities, and re-enabling JEIDs, it still caused the error code. I'm unsure if there was any other mod causing JEIDs to start giving me this error.

The screenshot is the exact error code I received. If the list of mods I have is needed, please ask me and I will send it.

![Screenshot_1](https://user-images.githubusercontent.com/62733241/77717264-622bf380-6fb6-11ea-93bc-5dba2ff84a82.png)

**Comment by Archilyte** [comment] 2020-04-01 13:38
where is the crash log?
(press that big "get link" button to get it)

**Comment by Kalonachan** [comment] 2020-04-01 23:21
https://paste.dimdev.org/tunimesoze.mccrash
I'm unsure if this will open for you, but here's the log. If it doesn't
work, i'll send screenshots of the entire page.

**Comment by Archilyte** [comment] 2020-04-02 00:22
check if rolling back the version from 1.0.3-54 to 1.0.3-48 fixes issue

**Comment by sam-kirby** [comment] 2020-04-02 00:33
This is an issue with conflicting versions of the Mixin library used in the latest version of the mod and the Mixin library that has been loaded by another mod in the pack, possibly VanillaFix.

Reverting to 1.0.3-52 or earlier, or removing other mods that load an earlier version of the Mixin library will resolve this for the time being.

Duplicate of #121

**Closed by sam-kirby** 2020-04-02 00:33 UTC
