### ISSUE TITLE
Crash when breaking a bee hive with Just Enough ids installed

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/JustEnoughIDs#15] opened 2018-07-01 19:39 UTC
Not sure if this is a crash from your mod or there's 

https://gist.github.com/TacticalUniverse/ed587f284c18fa8f5c0cd771808fd031

**Comment by Robijnvogel** [comment] 2018-07-01 19:41
Duplicate of #7

**Closed** 2018-07-01 19:41 UTC
Labels: duplicate
