### ISSUE TITLE
Possible conflict with newer builds of the twilight forest

### ISSUE THREAD

**Issue by Sunconure11** [DimensionalDevelopment/JustEnoughIDs#52] opened 2019-01-12 12:00 UTC
https://github.com/TeamTwilight/twilightforest/issues/685

**Comment by Xalcon** [comment] 2019-01-22 21:04
This is caused by a change to [BlockTFMagicLogSpecial#sendChangedBiome()](https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/block/BlockTFMagicLogSpecial.java#L158)
The method now accepts an additional Biome parameter and because of this, the mixin library crashes with a InvalidMixingException. This sounds like an easy fix but I'm not sure if there is more that needs to be done. The sendChangedBiome method also changed slighly since it now passes `pos.getY()` instead of `128.0` around.
https://github.com/TeamTwilight/twilightforest/commit/a8c4575fe3e73bce257cec35d505e2b7a458f4db#diff-3726bc9a77a4b68c44c0c3bdeb7cd63eR159

**Comment by TacticalUniverse** [comment] 2019-01-30 04:40
@Runemoro Any updated on if this or other JustEnoughIDs issues are being fixed or worked on

**Comment by Modpack-Support** [comment] 2019-02-04 22:15
@ZombieHDGaming any update is this is being worked on

**Comment by gudenau** [comment] 2019-02-18 21:57
I also have this issue, what is the latest version of The Twilight Forest that supports this?

**Comment by viceroy369** [comment] 2019-02-25 02:39
Under what circumstance does this crash occur? I tried the newest TF+JEID in single player and it seems to be working just fine??

**Comment by Xalcon** [comment] 2019-02-25 11:49
@viceroy369 are you sure you used the latest versions of both? Twilight Forest 3.8.689 does indeed work, but it's not the **latest** version.
Installing the minimal setup with the following versions will crash on startup:
* JustEnoughIDs-1.0.2-26
* twilightforest-1.12.2-3.9.851-universal
  * CTM-MC1.12.2-0.3.3.22
  * Patchouli-1.0-17
It even crashes if you remove twilight forests dependencies (I assume the crash happens before forge could check the dependencies)
```
[12:48:03] [Client thread/FATAL]: Mixin apply failed mixins.jeid.modsupport.json:MixinBlockTFMagicLogSpecial -> twilightforest.block.BlockTFMagicLogSpecial: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Overwrite target "sendChangedBiome" was not located in target class twilightforest/block/BlockTFMagicLogSpecial
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "sendChangedBiome" was not located in target class twilightforest/block/BlockTFMagicLogSpecial
```

**Comment by viceroy369** [comment] 2019-02-25 18:03
Derp. Hadn't notice TF had a new build out. Yes the latest version crashes.

**Comment by johnneijzen** [comment] 2019-03-23 11:50
same here if use latest version TF is crashes but release version works fine

**Comment by TheRealDadbeard** [comment] 2019-04-11 12:39
any update on this one?

**Comment by Sunconure11** [comment] 2019-04-11 14:39
There's an add on for JEID that fixes this

**Comment by TheRealDadbeard** [comment] 2019-04-11 14:50
huh okay where?? Is there any addon too for fixing broken biomes names? It was a long time since this has been updated and I can't just remove it...

**Comment by ZombieHDGaming** [comment] 2019-04-17 21:30
Fixed in latest commits.

**Closed by ZombieHDGaming** 2019-04-17 21:30 UTC

**Comment by Saereth** [comment] 2019-04-23 15:57
any chance on a new cf build for this soon? last cf build was like october of last year.

**Comment by DeadSix27** [comment] 2019-04-23 16:01
You could just use the GH release:
<https://github.com/DimensionalDevelopment/JustEnoughIDs/releases>

BUT those seem to not work for me. I still have to use JEID (old ver) + that JEID addon to fix this.

**Comment by Saereth** [comment] 2019-04-23 16:02
whats the jeid addon that uses it? and no cant release a pack on twitch with unsupported builds (on cf), well you can but you gotta go through the 3rd party permission system which is a pita

**Comment by DeadSix27** [comment] 2019-04-23 16:03
there: https://minecraft.curseforge.com/projects/justenoughids-integration-jeidsi/files

**Comment by ZombieHDGaming** [comment] 2019-04-23 16:06
@DeadSix27 are you sure you're even using the latest release for the JEID dev builds? Cause JEIDsI won't do anything since those fixes were combined with ours with the permission of the dev who wrote the addon

**Comment by DeadSix27** [comment] 2019-04-23 16:07
@ZombieHDGaming Yes, I've even build it myself from git master to make sure, doesn't work still.

**Comment by ZombieHDGaming** [comment] 2019-04-24 19:08
Once the dev build is done building, give that a try. It should work perfectly now from my tests.
